### ISSUE TITLE
Error while using translate

### ISSUE THREAD

**Issue by delusion8399** [crate/mongodb-cratedb-migration-tool#25] opened 2024-03-11 11:19 UTC
Hi, getting this error while using translate

    type = max(types, key=lambda item: types[item]["count"])
ValueError: max() arg is an empty sequence

![image](https://github.com/crate/mongodb-cratedb-migration-tool/assets/38590876/5009521c-125b-4a4d-9184-2e69d0d70e8c)

**Comment by amotl** [comment] 2024-04-08 19:59
Dear Shahid,

we are archiving this repository, because the code has been refactored into the `cratedb-toolkit` package. You can find corresponding documentation at:

- https://github.com/crate-workbench/cratedb-toolkit/blob/v0.0.9/cratedb_toolkit/io/mongodb/README.md
- https://github.com/crate-workbench/cratedb-toolkit/tree/v0.0.9/cratedb_toolkit/io#mongodb

Therefore, we also transferred your report, to be located here now.

- https://github.com/crate-workbench/cratedb-toolkit/issues/134

It would be sweet to investigate the root cause of this problem together, but we will likely need more information about your environment.

With kind regards,
Andreas.

**Closed as not planned by amotl** 2024-04-08 19:59 UTC
